# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbseer < Formula
  desc "Lightweight browser-based Postgres GUI for dev environments"
  homepage "https://github.com/zackbart/dbseer"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.3/dbseer_0.1.3_darwin_amd64.tar.gz"
      sha256 "e50332a8d878dcd6e29e013f82dd845dab7bf5fd381f590fde66d846e19d93de"

      define_method(:install) do
        bin.install "dbseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.3/dbseer_0.1.3_darwin_arm64.tar.gz"
      sha256 "b5f007a895303d75b234c1a6d6bb5286e46181d240561df795b1416a208c2ac1"

      define_method(:install) do
        bin.install "dbseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.3/dbseer_0.1.3_linux_amd64.tar.gz"
      sha256 "a4ebf88a1d086336c8605c8de8c7b77df329939029c8993e24ff9233c1686616"
      define_method(:install) do
        bin.install "dbseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.3/dbseer_0.1.3_linux_arm64.tar.gz"
      sha256 "578714fbecf2b6abb375fce01d283a82a49056753090692d627ff7ff4cf6543f"
      define_method(:install) do
        bin.install "dbseer"
      end
    end
  end

  test do
    assert_match "dbseer v#{version}", shell_output("#{bin}/dbseer --version")
  end
end
