# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbseer < Formula
  desc "Lightweight browser-based Postgres GUI for dev environments"
  homepage "https://github.com/zackbart/dbseer"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.4/dbseer_0.1.4_darwin_amd64.tar.gz"
      sha256 "8f31a95da50f0c8c0afd512288f9d9af8283817ca54dd21107dfa9ad924f789b"

      define_method(:install) do
        bin.install "dbseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.4/dbseer_0.1.4_darwin_arm64.tar.gz"
      sha256 "cb841b1f3c6d052bc1c86e4acf7524e05bf75d3d5179474eea6286219c570da9"

      define_method(:install) do
        bin.install "dbseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.4/dbseer_0.1.4_linux_amd64.tar.gz"
      sha256 "08ac8ad8f7bd4c959f2f1556b7545a3f102e3861de322f1977f7e03ee70295f3"
      define_method(:install) do
        bin.install "dbseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.4/dbseer_0.1.4_linux_arm64.tar.gz"
      sha256 "78f989b1973f19eae9dfbe55c9a5d29341541b88f52b64d7a6a25b8e4aa9d9eb"
      define_method(:install) do
        bin.install "dbseer"
      end
    end
  end

  test do
    assert_match "dbseer v#{version}", shell_output("#{bin}/dbseer --version")
  end
end
