# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbseer < Formula
  desc "Lightweight browser-based Postgres GUI for dev environments"
  homepage "https://github.com/zackbart/dbseer"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.1/dbseer_0.1.1_darwin_amd64.tar.gz"
      sha256 "b648bc1e638243cebf03616acbd352793ec4784a2209721569f4b53b3948dd9e"

      define_method(:install) do
        bin.install "dbseer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.1/dbseer_0.1.1_darwin_arm64.tar.gz"
      sha256 "8253130d61022f193410ce189cddeb2a503d0060a3587af76a799ad33dd83996"

      define_method(:install) do
        bin.install "dbseer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.1/dbseer_0.1.1_linux_amd64.tar.gz"
      sha256 "378ab92ec72f762912f86e93491ead4ea6431f8c20b96f60bc3bb3913733ce5e"
      define_method(:install) do
        bin.install "dbseer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/dbseer/releases/download/v0.1.1/dbseer_0.1.1_linux_arm64.tar.gz"
      sha256 "879a437d707f9ecf9eab46c54c14e3be207126aea7ceee40b8ce4b3a0b0cf978"
      define_method(:install) do
        bin.install "dbseer"
      end
    end
  end

  test do
    assert_match "dbseer v#{version}", shell_output("#{bin}/dbseer --version")
  end
end
