# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seer < Formula
  desc "A dead-simple TUI for browsing directories and previewing files"
  homepage "https://github.com/zackbart/seer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/seer/releases/download/v0.1.0/seer_0.1.0_darwin_amd64.tar.gz"
      sha256 "fb4c78869e7b5b8036ae9052da14753e55bb464c778ac3d70de7e06a0e16e172"

      define_method(:install) do
        bin.install "seer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/seer/releases/download/v0.1.0/seer_0.1.0_darwin_arm64.tar.gz"
      sha256 "3b911baa00204406f0ba6a280e7bc782d4500b5b00821f81ad820dea7c1f0c7e"

      define_method(:install) do
        bin.install "seer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/seer/releases/download/v0.1.0/seer_0.1.0_linux_amd64.tar.gz"
      sha256 "c31ad2da1f5865ca5a67eb1b1f4de9e5fc61fafd84edcb18a2dbe2124ec14948"
      define_method(:install) do
        bin.install "seer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/seer/releases/download/v0.1.0/seer_0.1.0_linux_arm64.tar.gz"
      sha256 "21bc861f4c6e47638617a7f788bba34f405e1754f1a47cc7cd2d49164065bece"
      define_method(:install) do
        bin.install "seer"
      end
    end
  end

  test do
    assert_predicate testpath/"#{bin}/seer", :exist?
  end
end
