# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seer < Formula
  desc "A dead-simple TUI for browsing directories and previewing files"
  homepage "https://github.com/zackbart/seer"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/seer/releases/download/v0.2.0/seer_0.2.0_darwin_amd64.tar.gz"
      sha256 "40e6847264491a061261751bbc048e43fddbc923c42586b8de6aa0388ad7404d"

      define_method(:install) do
        bin.install "seer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/seer/releases/download/v0.2.0/seer_0.2.0_darwin_arm64.tar.gz"
      sha256 "058c8aa99abc5a1178b876847d5574f7ff5d0458718b89692f252daac763ad5a"

      define_method(:install) do
        bin.install "seer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/seer/releases/download/v0.2.0/seer_0.2.0_linux_amd64.tar.gz"
      sha256 "75bbd584374bfb0a596a8fd74bbb12add76ac602a31b1b5de7ef3debfe7bc92b"
      define_method(:install) do
        bin.install "seer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/seer/releases/download/v0.2.0/seer_0.2.0_linux_arm64.tar.gz"
      sha256 "1161a267f2b4865f7f36b1d46829037b6ea1428be3238877d293931b0cbf78ec"
      define_method(:install) do
        bin.install "seer"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/seer --version")
  end
end
