# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Werk < Formula
  desc "Local-first task and decision tracker for AI-assisted development"
  homepage "https://github.com/zackbart/werk"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/werk/releases/download/v0.1.0/werk_0.1.0_darwin_amd64.tar.gz"
      sha256 "84522ad5a5b280c56d06803ea337758b545d3117919a08556d18214040f9280c"

      define_method(:install) do
        bin.install "werk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/werk/releases/download/v0.1.0/werk_0.1.0_darwin_arm64.tar.gz"
      sha256 "2172b36fc12bb9c955c572f24fce03e874fff54785a7b1ff502a7f3f8be43235"

      define_method(:install) do
        bin.install "werk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/werk/releases/download/v0.1.0/werk_0.1.0_linux_amd64.tar.gz"
      sha256 "d930027d94bea801f76b65125049a5389dd2ac6f557c6463cf9a788ae98a8e0f"
      define_method(:install) do
        bin.install "werk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/werk/releases/download/v0.1.0/werk_0.1.0_linux_arm64.tar.gz"
      sha256 "a77b7aeb74051da4a64dd7ef617c905b8364308e564b1bb58744b8fc3aab9bd8"
      define_method(:install) do
        bin.install "werk"
      end
    end
  end

  test do
    system "#{bin}/werk", "--version"
  end
end
