# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Werk < Formula
  desc "Local-first task and decision tracker for AI-assisted development"
  homepage "https://github.com/zackbart/werk"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/werk/releases/download/v0.1.1/werk_0.1.1_darwin_amd64.tar.gz"
      sha256 "4ca1694dd97648e90590b63c18a04e46ea560715b65fdbca038271db65416edb"

      define_method(:install) do
        bin.install "werk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/werk/releases/download/v0.1.1/werk_0.1.1_darwin_arm64.tar.gz"
      sha256 "363336d3fa8a66abfdf89c43bb76513f9f59db6cf71aa0ef929af3f30fee927a"

      define_method(:install) do
        bin.install "werk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/werk/releases/download/v0.1.1/werk_0.1.1_linux_amd64.tar.gz"
      sha256 "371d18d24325cd6c57a774a92abfd98fdd0623840606a880426ce3f06e60428c"
      define_method(:install) do
        bin.install "werk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/werk/releases/download/v0.1.1/werk_0.1.1_linux_arm64.tar.gz"
      sha256 "2b999a25313dcd095fefcb438a3e4230cef51b9cc09eef8afccd2fceb71441da"
      define_method(:install) do
        bin.install "werk"
      end
    end
  end

  test do
    system "#{bin}/werk", "--version"
  end
end
