# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Werk < Formula
  desc "Local-first task and decision tracker for AI-assisted development"
  homepage "https://github.com/zackbart/werk"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zackbart/werk/releases/download/v0.3.0/werk_0.3.0_darwin_amd64.tar.gz"
      sha256 "0d6414e518376803007da516d6947298ecff76364b58de117867ed5f91636945"

      define_method(:install) do
        bin.install "werk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zackbart/werk/releases/download/v0.3.0/werk_0.3.0_darwin_arm64.tar.gz"
      sha256 "0b7214ac5508a1f1542e44fbab00d5d22dc4c878e1ed64e961e92a3fcb21a893"

      define_method(:install) do
        bin.install "werk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/werk/releases/download/v0.3.0/werk_0.3.0_linux_amd64.tar.gz"
      sha256 "4968ae28babd02bcdceff9f2970da3f74c4675b044d35047b6c1bddc2efdab38"
      define_method(:install) do
        bin.install "werk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zackbart/werk/releases/download/v0.3.0/werk_0.3.0_linux_arm64.tar.gz"
      sha256 "002b392b2ee5cf58899a9d910d6ceff4e125d0579fa246d6038db45b1d868e79"
      define_method(:install) do
        bin.install "werk"
      end
    end
  end

  test do
    system "#{bin}/werk", "--version"
  end
end
